version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: adventureworks-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: adventureworks-frontend
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://backend:8000
